DO SLEEP(0.125);
-- Insert Addresses
INSERT INTO
    tb_address (
        created_at,
        created_by,
        deleted,
        deleted_at,
        scope,
        tenant_group_id,
        tenant_id,
        updated_at,
        updated_by,
        version,
        bairro,
        cep,
        cidade,
        complemento,
        estado,
        numero,
        principal,
        rua,
        tipo
    )
VALUES
    -- BusinessPartner Addresses
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Centro',
        '01310100',
        'São Paulo',
        'Apto 1001',
        'SP',
        '100',
        1,
        'Avenida Paulista',
        'COMERCIAL'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Vila Mariana',
        '04016903',
        'São Paulo',
        'Bloco A',
        'SP',
        '250',
        0,
        'Rua Vergueiro',
        'ENTREGA'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Bom Retiro',
        '01311100',
        'São Paulo',
        NULL,
        'SP',
        '500',
        1,
        'Rua 25 de Março',
        'COMERCIAL'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Jardins',
        '01445000',
        'São Paulo',
        'Fundos',
        'SP',
        '1000',
        1,
        'Rua Augusta',
        'RESIDENCIAL'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Pinheiros',
        '05429100',
        'São Paulo',
        NULL,
        'SP',
        '150',
        0,
        'Avenida Pedroso de Morais',
        'COBRANCA'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Consolação',
        '01311100',
        'São Paulo',
        NULL,
        'SP',
        '900',
        1,
        'Rua da Consolação',
        'CORRESPONDENCIA'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Republica',
        '01310100',
        'São Paulo',
        'Sala 300',
        'SP',
        '200',
        1,
        'Avenida Rio Branco',
        'COMERCIAL'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Liberdade',
        '01509000',
        'São Paulo',
        NULL,
        'SP',
        '880',
        0,
        'Rua Galvão Bueno',
        'ENTREGA'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Tatuapé',
        '03308040',
        'São Paulo',
        NULL,
        'SP',
        '1500',
        1,
        'Avenida Salim Farah Maluf',
        'COMERCIAL'
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        'Vila Madalena',
        '05435100',
        'São Paulo',
        'Casa 5',
        'SP',
        '580',
        1,
        'Rua Inácio Pereira da Rocha',
        'RESIDENCIAL'
    );