CREATE TABLE
  tb_business_partner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      limite_credito FLOAT (53),
      limite_desconto FLOAT (53),
      protestado BOOLEAN,
      restricao_financeira BOOLEAN,
      aliquota_icms FLOAT (53),
      cnae_principal VARCHAR(255),
      cnpj VARCHAR(14),
      consumidor_final BOOLEAN,
      cpf VARCHAR(11),
      icms_contribuinte BOOLEAN,
      inscricao_estadual VARCHAR(255),
      inscricao_municipal VARCHAR(255),
      nome_fantasia VARCHAR(255),
      razao_social VARCHAR(255),
      regime_tributario VARCHAR(255) CHECK (
        (
          regime_tributario IN (
            'SIMPLES_NACIONAL',
            'LUCRO_REAL',
            'LUCRO_PRESUMIDO',
            'MEI',
            'LUCRO_ARBITRADO'
          )
        )
      ),
      rg VARCHAR(9),
      nome VARCHAR(255) NOT NULL,
      email_nfe VARCHAR(255),
      email_principal VARCHAR(255),
      enviar_email BOOLEAN,
      mala_direta BOOLEAN,
      status VARCHAR(255) NOT NULL CHECK ((status IN ('ATIVO', 'INATIVO', 'BLOQUEADO'))),
      tipo VARCHAR(255) NOT NULL CHECK (
        (
          tipo IN ('PESSOA_FISICA', 'PESSOA_JURIDICA', 'AMBOS')
        )
      ),
      PRIMARY KEY (id)
  );

CREATE TABLE
  TB_BUSINESS_PARTNER_CONTACT (
    businesspartner_id BIGINT NOT NULL,
    contact_id BIGINT NOT NULL
  );

CREATE TABLE
  TB_BUSINESS_PARTNER_ADDRESS (
    businesspartner_id BIGINT NOT NULL,
    address_id BIGINT NOT NULL
  );

CREATE TABLE
  tb_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      ativo BOOLEAN NOT NULL,
      descricao VARCHAR(255),
      principal BOOLEAN NOT NULL,
      tipo VARCHAR(255) NOT NULL CHECK (
        (
          tipo IN (
            'TELEFONE',
            'CELULAR',
            'EMAIL',
            'WHATSAPP',
            'LINKEDIN',
            'INSTAGRAM',
            'FACEBOOK',
            'WEBSITE',
            'OUTRO'
          )
        )
      ),
      valor VARCHAR(255) NOT NULL,
      PRIMARY KEY (id)
  );

CREATE TABLE
  TB_CUSTOM_DATA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    value oid,
    custom_field_id BIGINT,
    entity_id BIGINT NOT NULL,
    custom_data_id BIGINT,
    PRIMARY KEY (id)
  );

CREATE TABLE
  TB_custom_field_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      active BOOLEAN,
      field_key VARCHAR(255),
      field_order INTEGER,
      field_type VARCHAR(255) CHECK (
        (
          field_type IN (
            'TEXT',
            'NUMBER',
            'DATE',
            'BOOLEAN',
            'SELECT',
            'MULTI_SELECT',
            'EMAIL'
          )
        )
      ),
      label VARCHAR(255),
      metadata VARCHAR(255),
      required BOOLEAN,
      target VARCHAR(255),
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      bairro VARCHAR(100) NOT NULL,
      cep VARCHAR(8) NOT NULL,
      cidade VARCHAR(100) NOT NULL,
      complemento VARCHAR(255),
      estado VARCHAR(2) NOT NULL,
      numero VARCHAR(50) NOT NULL,
      principal BOOLEAN NOT NULL,
      rua VARCHAR(255) NOT NULL,
      tipo VARCHAR(255) NOT NULL CHECK (
        (
          tipo IN (
            'RESIDENCIAL',
            'COMERCIAL',
            'ENTREGA',
            'COBRANCA',
            'CORRESPONDENCIA',
            'OUTRO'
          )
        )
      ),
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      acao VARCHAR(255) NOT NULL CHECK (
        (
          acao IN (
            'VISUALIZAR',
            'CRIAR',
            'EDITAR',
            'EXCLUIR',
            'OUTRO'
          )
        )
      ),
      codigo VARCHAR(255) NOT NULL,
      modulo VARCHAR(255) NOT NULL,
      nome VARCHAR(255) NOT NULL,
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      cest VARCHAR(7),
      codigo_beneficio_fiscal VARCHAR(10),
      descricao_fiscal VARCHAR(120) NOT NULL,
      ncm VARCHAR(8) NOT NULL,
      origem_mercadoria INTEGER NOT NULL,
      unidade_tributavel_codigo VARCHAR(6) NOT NULL,
      unidade_tributavel_descricao VARCHAR(60) NOT NULL,
      codigo VARCHAR(50) NOT NULL,
      descricao VARCHAR(255) NOT NULL,
      descricaoDetalhada TEXT,
      precoCusto DECIMAL(10, 2),
      precoVenda DECIMAL(10, 2),
      status VARCHAR(255) NOT NULL CHECK (
        (
          status IN ('ATIVO', 'INATIVO', 'BLOQUEADO', 'DESCONTINUADO')
        )
      ),
      type VARCHAR(255) NOT NULL CHECK ((type IN ('COMPRADO', 'FABRICAVEL'))),
      measure_unit_id BIGINT NOT NULL,
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_product_composition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dataAtualizacao TIMESTAMP(6)
    WITH
      TIME ZONE NOT NULL,
      dataCriacao TIMESTAMP(6)
    WITH
      TIME ZONE NOT NULL,
      observacoes VARCHAR(500),
      quantidadeNecessaria DECIMAL(10, 4) NOT NULL,
      sequencia INTEGER NOT NULL,
      product_componente_id BIGINT NOT NULL,
      product_fabricado_id BIGINT NOT NULL,
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      nome VARCHAR(255) NOT NULL,
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_role_permission (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
  );

CREATE TABLE
  tb_measure_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      descricao VARCHAR(100) NOT NULL,
      sigla VARCHAR(10) NOT NULL,
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      created_by BIGINT,
      deleted BOOLEAN,
      deleted_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      scope VARCHAR(255) CHECK ((scope IN ('GLOBAL', 'GROUP', 'TENANT'))),
      tenant_group_id BIGINT,
      tenant_id BIGINT NOT NULL,
      updated_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      updated_by BIGINT,
      version BIGINT,
      approved_at TIMESTAMP(6)
    WITH
      TIME ZONE,
      aprovado_por BIGINT,
      cpf VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      nome_completo VARCHAR(255) NOT NULL,
      senha_hash VARCHAR(255) NOT NULL,
      status VARCHAR(255) NOT NULL CHECK (
        (
          status IN (
            'ATIVO',
            'INATIVO',
            'PENDENTE_APROVACAO',
            'REJEITADO',
            'BLOQUEADO'
          )
        )
      ),
      PRIMARY KEY (id)
  );

CREATE TABLE
  tb_user_contact (
    user_id BIGINT NOT NULL,
    contact_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, contact_id)
  );

CREATE TABLE
  tb_user_permission (
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, permission_id)
  );

CREATE TABLE
  tb_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
  );

ALTER TABLE TB_BUSINESS_PARTNER_CONTACT ADD CONSTRAINT UKoyvoyiovpks7mak7a6o9shsjf UNIQUE (contact_id);

ALTER TABLE TB_BUSINESS_PARTNER_ADDRESS ADD CONSTRAINT UK3g4mi2jwv887g1adobbi2ty7j UNIQUE (address_id);

ALTER TABLE tb_permission ADD CONSTRAINT UK1uq3cg2rbrpk3ykinkkju2gaw UNIQUE (codigo);

ALTER TABLE tb_product ADD CONSTRAINT UK472kg512c3fntgnpuqi1wk1l2 UNIQUE (codigo);

ALTER TABLE tb_role ADD CONSTRAINT UK6e9vttep485ay7pmjccprgdus UNIQUE (nome);

ALTER TABLE tb_measure_unit ADD CONSTRAINT UKqpb3oc1tcjwvcj76341nv6tl3 UNIQUE (sigla);

ALTER TABLE tb_user ADD CONSTRAINT UK594wib8ansybtilla48x7vdld UNIQUE (cpf);

ALTER TABLE tb_user ADD CONSTRAINT UKspmnyb4dsul95fjmr5kmdmvub UNIQUE (email);

ALTER TABLE TB_BUSINESS_PARTNER_CONTACT ADD CONSTRAINT FKar3q0fwokcc43i1w07alv1u9t FOREIGN key (contact_id) REFERENCES tb_contacts (id);

ALTER TABLE TB_BUSINESS_PARTNER_CONTACT ADD CONSTRAINT FKf44b9l0vsi0mdpwwwla1sfx27 FOREIGN key (businesspartner_id) REFERENCES tb_business_partner (id);

ALTER TABLE TB_BUSINESS_PARTNER_ADDRESS ADD CONSTRAINT FKh4pilbdgv2i62kt67lignqxat FOREIGN key (address_id) REFERENCES tb_address (id);

ALTER TABLE TB_BUSINESS_PARTNER_ADDRESS ADD CONSTRAINT FKe9hd85a57v19b97k79s98yqr8 FOREIGN key (businesspartner_id) REFERENCES tb_business_partner (id);

ALTER TABLE TB_CUSTOM_DATA ADD CONSTRAINT FKl4dh8wnk2ggj2muhk8ejclagn FOREIGN key (custom_field_id) REFERENCES TB_custom_field_definition (id);

ALTER TABLE TB_CUSTOM_DATA ADD CONSTRAINT FKdo0o08go0vcg0t8gty92res9f FOREIGN key (custom_data_id) REFERENCES TB_CUSTOM_DATA (id);

ALTER TABLE TB_CUSTOM_DATA ADD CONSTRAINT FKfwqipgg4jncq8uernqmtmuj11 FOREIGN key (entity_id) REFERENCES tb_product (id);

ALTER TABLE tb_product ADD CONSTRAINT FKjm741es56cwngwn3hsr15uqew FOREIGN key (measure_unit_id) REFERENCES tb_measure_unit (id);

ALTER TABLE tb_product_composition ADD CONSTRAINT FKp0ouw2m2gjdkq1ifxqeewbu1d FOREIGN key (product_componente_id) REFERENCES tb_product (id);

ALTER TABLE tb_product_composition ADD CONSTRAINT FKwol2pcy2wvmbq3q7x99dn1lp FOREIGN key (product_fabricado_id) REFERENCES tb_product (id);

ALTER TABLE tb_role_permission ADD CONSTRAINT FK1i43spbowu8fpdli5h311a97u FOREIGN key (permission_id) REFERENCES tb_permission (id);

ALTER TABLE tb_role_permission ADD CONSTRAINT FKshhi66xugi1k1chvvygj4of5r FOREIGN key (role_id) REFERENCES tb_role (id);

ALTER TABLE tb_user_contact ADD CONSTRAINT FK3gh0ltuf1syctfafopd94dqlg FOREIGN key (contact_id) REFERENCES tb_contacts (id);

ALTER TABLE tb_user_contact ADD CONSTRAINT FK128rl735ifi2ei19hvl9gv6gc FOREIGN key (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_user_permission ADD CONSTRAINT FKduh5ix0b4v9ns4ehping4wl68 FOREIGN key (permission_id) REFERENCES tb_permission (id);

ALTER TABLE tb_user_permission ADD CONSTRAINT FKse5klwt0ivx37h6opgx6ipjuw FOREIGN key (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_user_role ADD CONSTRAINT FKkix4nwaehqjwnk40e2e36903j FOREIGN key (role_id) REFERENCES tb_role (id);

ALTER TABLE tb_user_role ADD CONSTRAINT FKj4syki71kai6syrfuly9xfcq FOREIGN key (user_id) REFERENCES tb_user (id);