-- ==================================================================================
-- MIGRATION: V4__Seed_Unidades_Medida.sql (Tenant)
-- DESCRIÇÃO: Insere unidades de medida padrão
-- APLICÁVEL: Todos os tenants
-- ==================================================================================
INSERT IGNORE INTO unidade_medida (sigla, descricao, ativo)
VALUES
    ('AMPOLA', 'AMPOLA', TRUE),
    ('BALDE', 'BALDE', TRUE),
    ('BANDEJ', 'BANDEJA', TRUE),
    ('BARRA', 'BARRA', TRUE),
    ('BISNAG', 'BISNAGA', TRUE),
    ('BLOCO', 'BLOCO', TRUE),
    ('BOBINA', 'BOBINA', TRUE),
    ('BOMB', 'BOMBONA', TRUE),
    ('CAPS', 'CAPSULA', TRUE),
    ('CART', 'CARTELA', TRUE),
    ('CENTO', 'CENTO', TRUE),
    ('CJ', 'CONJUNTO', TRUE),
    ('CM', 'CENTIMETRO', TRUE),
    ('CM2', 'CENTIMETRO QUADRADO', TRUE),
    ('CX', 'CAIXA', TRUE),
    ('CX2', 'CAIXA COM 2 UNIDADES', TRUE),
    ('CX3', 'CAIXA COM 3 UNIDADES', TRUE),
    ('CX5', 'CAIXA COM 5 UNIDADES', TRUE),
    ('CX10', 'CAIXA COM 10 UNIDADES', TRUE),
    ('CX15', 'CAIXA COM 15 UNIDADES', TRUE),
    ('CX20', 'CAIXA COM 20 UNIDADES', TRUE),
    ('CX25', 'CAIXA COM 25 UNIDADES', TRUE),
    ('CX50', 'CAIXA COM 50 UNIDADES', TRUE),
    ('CX100', 'CAIXA COM 100 UNIDADES', TRUE),
    ('DISP', 'DISPLAY', TRUE),
    ('DUZIA', 'DUZIA', TRUE),
    ('EMBAL', 'EMBALAGEM', TRUE),
    ('FARDO', 'FARDO', TRUE),
    ('FOLHA', 'FOLHA', TRUE),
    ('FRASCO', 'FRASCO', TRUE),
    ('GALAO', 'GALÃO', TRUE),
    ('GF', 'GARRAFA', TRUE),
    ('GRAMAS', 'GRAMAS', TRUE),
    ('JOGO', 'JOGO', TRUE),
    ('KG', 'QUILOGRAMA', TRUE),
    ('KIT', 'KIT', TRUE),
    ('LATA', 'LATA', TRUE),
    ('LITRO', 'LITRO', TRUE),
    ('M', 'METRO', TRUE),
    ('M2', 'METRO QUADRADO', TRUE),
    ('M3', 'METRO CÚBICO', TRUE),
    ('MILHEI', 'MILHEIRO', TRUE),
    ('ML', 'MILILITRO', TRUE),
    ('MWH', 'MEGAWATT HORA', TRUE),
    ('PACOTE', 'PACOTE', TRUE),
    ('PALETE', 'PALETE', TRUE),
    ('PARES', 'PARES', TRUE),
    ('PC', 'PEÇA', TRUE),
    ('POTE', 'POTE', TRUE),
    ('K', 'QUILATE', TRUE),
    ('RESMA', 'RESMA', TRUE),
    ('ROLO', 'ROLO', TRUE),
    ('SACO', 'SACO', TRUE),
    ('SACOLA', 'SACOLA', TRUE),
    ('TAMBOR', 'TAMBOR', TRUE),
    ('TANQUE', 'TANQUE', TRUE),
    ('TON', 'TONELADA', TRUE),
    ('TUBO', 'TUBO', TRUE),
    ('UNID', 'UNIDADE', TRUE),
    ('VASIL', 'VASILHAME', TRUE),
    ('VIDRO', 'VIDRO', TRUE);