-- Insert Products
INSERT INTO
    tb_product (
        created_at,
        created_by,
        deleted,
        deleted_at,
        scope,
        tenant_group_id,
        tenant_id,
        updated_at,
        updated_by,
        version,
        cest,
        codigo_beneficio_fiscal,
        descricao_fiscal,
        ncm,
        origem_mercadoria,
        unidade_tributavel_codigo,
        unidade_tributavel_descricao,
        codigo,
        descricao,
        descricaoDetalhada,
        precoCusto,
        precoVenda,
        status,
        type,
        measure_unit_id
    )
VALUES
    -- Eletrônicos
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'TELEVISOR 50 POLEGADAS',
        '85289200',
        0,
        'UNID',
        'Unidade',
        'PROD001',
        'Televisor LED 50"',
        'Televisor LED Full HD 50 polegadas com Smart TV',
        1200.00,
        1999.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'NOTEBOOK 15.6 POLEGADAS',
        '84714300',
        0,
        'UNID',
        'Unidade',
        'PROD002',
        'Notebook Core i7 15.6"',
        'Notebook 15.6 polegadas com processador Intel Core i7',
        2500.00,
        3499.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'MOUSE WIRELESS PRETO',
        '84716030',
        0,
        'UNID',
        'Unidade',
        'PROD003',
        'Mouse Wireless',
        'Mouse óptico wireless com alcance de 10 metros',
        25.00,
        49.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'TECLADO MECANICO RGB',
        '84716030',
        0,
        'UNID',
        'Unidade',
        'PROD004',
        'Teclado Mecânico RGB',
        'Teclado mecânico RGB com 104 teclas',
        150.00,
        299.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'MONITOR 24 IPS FULL HD',
        '85289200',
        0,
        'UNID',
        'Unidade',
        'PROD005',
        'Monitor 24" IPS',
        'Monitor 24 polegadas IPS Full HD resolução 1920x1080',
        600.00,
        899.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    -- Alimentos e Bebidas
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'CAFÉ 500G SOLVEL INSTANTANEO',
        '21011000',
        0,
        'UNID',
        'Unidade',
        'PROD006',
        'Café Solúvel 500g',
        'Café solúvel instantâneo 500 gramas',
        15.00,
        29.99,
        'ATIVO',
        'COMPRADO',
        2
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'LEITE INTEGRAL 1 LITRO',
        '04051000',
        0,
        'UNID',
        'Unidade',
        'PROD007',
        'Leite Integral 1L',
        'Leite integral pasteurizado 1 litro',
        3.50,
        5.99,
        'ATIVO',
        'COMPRADO',
        4
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'PÃO INTEGRAL 500G',
        '19051000',
        0,
        'UNID',
        'Unidade',
        'PROD008',
        'Pão Integral 500g',
        'Pão integral de forma 500 gramas',
        5.00,
        7.99,
        'ATIVO',
        'COMPRADO',
        2
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'SUCO NATURAL 1 LITRO',
        '20091009',
        0,
        'UNID',
        'Unidade',
        'PROD009',
        'Suco Natural 1L',
        'Suco natural 100% laranja 1 litro',
        6.00,
        9.99,
        'ATIVO',
        'COMPRADO',
        4
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'CHOCOLATE AO LEITE 200G',
        '18063100',
        0,
        'UNID',
        'Unidade',
        'PROD010',
        'Chocolate Ao Leite 200g',
        'Chocolate ao leite 200 gramas',
        8.00,
        14.99,
        'ATIVO',
        'COMPRADO',
        2
    ),
    -- Limpeza e Higiene
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'DETERGENTE NEUTRO 500ML',
        '34021900',
        0,
        'UNID',
        'Unidade',
        'PROD011',
        'Detergente Neutro 500ml',
        'Detergente neutro concentrado 500 mililitros',
        2.50,
        4.99,
        'ATIVO',
        'COMPRADO',
        5
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'SABÃO EM PÓ 1KG',
        '34021100',
        0,
        'UNID',
        'Unidade',
        'PROD012',
        'Sabão em Pó 1kg',
        'Sabão em pó 1 quilograma',
        8.00,
        12.99,
        'ATIVO',
        'COMPRADO',
        2
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'PAPEL HIGIENICO 4 ROLOS',
        '48181000',
        0,
        'UNID',
        'Unidade',
        'PROD013',
        'Papel Higiênico 4 rolos',
        'Papel higiênico 4 rolos duplos',
        5.00,
        8.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'SHAMPOO NEUTRO 200ML',
        '34052100',
        0,
        'UNID',
        'Unidade',
        'PROD014',
        'Shampoo Neutro 200ml',
        'Shampoo neutro para uso diário 200 mililitros',
        12.00,
        19.99,
        'ATIVO',
        'COMPRADO',
        5
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'SABONETE GLICERINA 90G',
        '34051900',
        0,
        'UNID',
        'Unidade',
        'PROD015',
        'Sabonete Glicerina 90g',
        'Sabonete de glicerina neutro 90 gramas',
        3.00,
        5.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    -- Vestuário
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'CAMISETA 100% ALGODAO BRANCA P',
        '61091000',
        0,
        'UNID',
        'Unidade',
        'PROD016',
        'Camiseta Branca Tam P',
        'Camiseta 100% algodão branca tamanho pequeno',
        25.00,
        49.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'CALCA JEANS AZUL M',
        '62034300',
        0,
        'UNID',
        'Unidade',
        'PROD017',
        'Calça Jeans Azul Tam M',
        'Calça jeans azul escuro tamanho médio',
        80.00,
        149.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'MEIA ALGODAO BRANCA 3 PARES',
        '61151900',
        0,
        'UNID',
        'Unidade',
        'PROD018',
        'Meia Algodão 3 Pares',
        'Meia 100% algodão branca pacote com 3 pares',
        15.00,
        24.99,
        'ATIVO',
        'COMPRADO',
        1
    ),
    -- Implementados (Fabricáveis)
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'KIT LIMPEZA COMPLETO',
        '34021900',
        0,
        'UNID',
        'Unidade',
        'PROD019',
        'Kit Limpeza Completo',
        'Kit com diversos produtos de limpeza',
        50.00,
        99.99,
        'ATIVO',
        'FABRICAVEL',
        1
    ),
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'KIT HIGIENE PESSOAL',
        '34051900',
        0,
        'UNID',
        'Unidade',
        'PROD020',
        'Kit Higiene Pessoal',
        'Kit com xampus, sabonetes e produtos de higiene pessoal',
        80.00,
        159.99,
        'ATIVO',
        'FABRICAVEL',
        1
    ),
    -- Inativo
    (
        CURRENT_TIMESTAMP,
        1,
        0,
        NULL,
        'TENANT',
        NULL,
        1,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        'DISCO RIGIDO EXTERNO 1TB',
        '84717030',
        0,
        'UNID',
        'Unidade',
        'PROD021',
        'Disco Rígido Externo 1TB',
        'Disco rígido externo 1TB descontinuado',
        200.00,
        399.99,
        'DESCONTINUADO',
        'COMPRADO',
        1
    );