-- V12__Create_New_Tenant_Model_Tables.sql
-- Refactoring do modelo de Tenant para arquitetura escalável com override de beans por tenant
-- 1. Tabela de Planos de Assinatura
CREATE TABLE IF NOT EXISTS
    tb_tnt_plan (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NAME VARCHAR(100) NOT NULL,
        description VARCHAR(500),
        monthly_price DECIMAL(10, 2) NOT NULL,
        max_users INTEGER NOT NULL,
        max_branches INTEGER NOT NULL,
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_plan_active ON tb_tnt_plan (active);


-- 2. Refactor da tabela principal de Tenant
-- IMPORTANTE: Esta migration assume que já existe tb_tenant. Ajustar conforme necessário.
-- Se tb_tenant não existir, criar:
CREATE TABLE IF NOT EXISTS
    tb_tnt (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NAME VARCHAR(200) NOT NULL,
        email VARCHAR(150) NOT NULL,
        phone VARCHAR(20),
        plan_id BIGINT NOT NULL REFERENCES tb_tnt_plan (id),
        active BOOLEAN NOT NULL DEFAULT TRUE,
        trial BOOLEAN NOT NULL DEFAULT FALSE,
        trial_expires_at TIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_active ON tb_tnt (active);


CREATE INDEX idx_tnt_plan_id ON tb_tnt (plan_id);


-- 3. Configurações gerais do Tenant
CREATE TABLE IF NOT EXISTS
    tb_tnt_config (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id BIGINT NOT NULL UNIQUE REFERENCES tb_tnt (id) ON DELETE CASCADE,
        slug VARCHAR(100) NOT NULL,
        app_name VARCHAR(150) NOT NULL,
        app_description VARCHAR(500),
        support_email VARCHAR(150),
        website_url VARCHAR(500),
        timezone VARCHAR(50) NOT NULL DEFAULT 'America/Sao_Paulo',
        locale VARCHAR(10) NOT NULL DEFAULT 'pt_BR',
        currency VARCHAR(3) NOT NULL DEFAULT 'BRL',
        date_format VARCHAR(20) NOT NULL DEFAULT 'dd/MM/yyyy',
        -- Módulos
        module_fiscal BOOLEAN NOT NULL DEFAULT TRUE,
        module_hr BOOLEAN NOT NULL DEFAULT FALSE,
        module_stock BOOLEAN NOT NULL DEFAULT FALSE,
        module_financial BOOLEAN NOT NULL DEFAULT FALSE,
        module_crm BOOLEAN NOT NULL DEFAULT FALSE,
        module_timesheet BOOLEAN NOT NULL DEFAULT FALSE,
        module_ecommerce BOOLEAN NOT NULL DEFAULT FALSE,
        -- Funcionalidades
        multi_branch BOOLEAN NOT NULL DEFAULT FALSE,
        allow_api_access BOOLEAN NOT NULL DEFAULT TRUE,
        white_label BOOLEAN NOT NULL DEFAULT FALSE,
        -- Notificações
        notify_email BOOLEAN NOT NULL DEFAULT TRUE,
        notify_sms BOOLEAN NOT NULL DEFAULT FALSE,
        notify_push BOOLEAN NOT NULL DEFAULT FALSE,
        notify_webhook BOOLEAN NOT NULL DEFAULT FALSE,
        -- Segurança e Autenticação
        two_factor_auth BOOLEAN NOT NULL DEFAULT FALSE,
        sso_enabled BOOLEAN NOT NULL DEFAULT FALSE,
        allow_social_login BOOLEAN NOT NULL DEFAULT FALSE,
        -- Status
        maintenance_mode BOOLEAN NOT NULL DEFAULT FALSE,
        onboarding_done BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_config_tenant_id ON tb_tnt_config (tenant_id);


-- 4. Identidade Visual do Tenant
CREATE TABLE IF NOT EXISTS
    tb_tnt_visual (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id BIGINT NOT NULL UNIQUE REFERENCES tb_tnt (id) ON DELETE CASCADE,
        theme VARCHAR(50) DEFAULT 'light',
        border_radius VARCHAR(20) DEFAULT '4px',
        sidebar_collapsed BOOLEAN NOT NULL DEFAULT FALSE,
        -- Cores
        color_primary VARCHAR(7),
        color_secondary VARCHAR(7),
        color_accent VARCHAR(7),
        color_background VARCHAR(7),
        color_text VARCHAR(7),
        color_danger VARCHAR(7),
        color_success VARCHAR(7),
        color_warning VARCHAR(7),
        -- Assets
        logo_url VARCHAR(500),
        logo_large_url VARCHAR(500),
        favicon_url VARCHAR(500),
        email_logo_url VARCHAR(500),
        background_image_url VARCHAR(500),
        -- Tipografia
        font_family VARCHAR(100),
        font_cdn_url VARCHAR(500),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_visual_tenant_id ON tb_tnt_visual (tenant_id);


-- 5. Datasource do Tenant
CREATE TABLE IF NOT EXISTS
    tb_tnt_datasource (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id BIGINT NOT NULL UNIQUE REFERENCES tb_tnt (id) ON DELETE CASCADE,
        driver_class VARCHAR(200) NOT NULL,
        url VARCHAR(500) NOT NULL,
        username VARCHAR(100) NOT NULL,
        password_encrypted VARCHAR(500) NOT NULL,
        schema_name VARCHAR(100),
        db_type VARCHAR(30) NOT NULL,
        pool_min INTEGER DEFAULT 5,
        pool_max INTEGER DEFAULT 20,
        connection_timeout INTEGER DEFAULT 30000,
        idle_timeout INTEGER DEFAULT 600000,
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_datasource_tenant_id ON tb_tnt_datasource (tenant_id);


CREATE INDEX idx_tnt_datasource_active ON tb_tnt_datasource (active);


-- 6. Domínios Permitidos
CREATE TABLE IF NOT EXISTS
    tb_tnt_allow_domains (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id BIGINT NOT NULL REFERENCES tb_tnt (id) ON DELETE CASCADE,
        DOMAIN VARCHAR(255) NOT NULL,
        TYPE VARCHAR(20) NOT NULL CHECK (
            TYPE IN ('EMAIL', 'CORS', 'SSO')
        ),
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_allow_domains_tenant_id ON tb_tnt_allow_domains (tenant_id);


CREATE UNIQUE INDEX idx_tnt_allow_domains_unique ON tb_tnt_allow_domains (tenant_id, DOMAIN);


-- 7. Dados Fiscais
CREATE TABLE IF NOT EXISTS
    tb_tnt_fiscal (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id BIGINT NOT NULL UNIQUE REFERENCES tb_tnt (id) ON DELETE CASCADE,
        cnpj VARCHAR(14) NOT NULL UNIQUE,
        legal_name VARCHAR(150) NOT NULL,
        trade_name VARCHAR(150),
        state_registration VARCHAR(20),
        city_registration VARCHAR(20),
        tax_regime VARCHAR(50),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_fiscal_tenant_id ON tb_tnt_fiscal (tenant_id);


CREATE INDEX idx_tnt_fiscal_cnpj ON tb_tnt_fiscal (cnpj);


-- 8. Política de Segurança
CREATE TABLE IF NOT EXISTS
    tb_tnt_security (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id BIGINT NOT NULL UNIQUE REFERENCES tb_tnt (id) ON DELETE CASCADE,
        -- Política de Senha
        min_password_length INTEGER DEFAULT 8,
        require_uppercase BOOLEAN NOT NULL DEFAULT TRUE,
        require_number BOOLEAN NOT NULL DEFAULT TRUE,
        require_special BOOLEAN NOT NULL DEFAULT FALSE,
        password_expiration_days INTEGER DEFAULT 90,
        -- Política de Lockout
        max_login_attempts INTEGER DEFAULT 5,
        lockout_duration_min INTEGER DEFAULT 15,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX idx_tnt_security_tenant_id ON tb_tnt_security (tenant_id);