-- V13__Create_Tenant_Features_Table.sql
-- Tabela central para override de beans Spring por tenant
-- Cada linha define: "para este tenant, quando pedir a feature 'featureKey', injete o bean 'beanName'"
CREATE TABLE IF NOT EXISTS
    tb_tnt_features (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id BIGINT NOT NULL REFERENCES tb_tnt (id) ON DELETE CASCADE,
        feature_key VARCHAR(100) NOT NULL,
        bean_name VARCHAR(200) NOT NULL,
        description VARCHAR(500),
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );


-- Constraint UNIQUE para garantir uma feature por tenant
CREATE UNIQUE INDEX idx_tnt_features_unique_per_tenant ON tb_tnt_features (tenant_id, feature_key);


-- Index para o resolver acessar features ativas rapidamente
CREATE INDEX idx_tnt_features_active ON tb_tnt_features (tenant_id, active)
WHERE
    active = TRUE;


-- Index genérico por tenant
CREATE INDEX idx_tnt_features_tenant_id ON tb_tnt_features (tenant_id);