CREATE TABLE TB_ADDRESS
(
    ID              BIGINT                                                                          NOT NULL AUTO_INCREMENT,
    CREATED_AT      DATETIME(6),
    CREATED_BY      BIGINT,
    DELETED         BIT,
    DELETED_AT      DATETIME(6),
    UPDATED_AT      DATETIME(6),
    UPDATED_BY      BIGINT,
    VERSION         BIGINT,
    SCOPE           ENUM ('GLOBAL','GROUP','TENANT'),
    TENANT_GROUP_ID BIGINT,
    TENANT_ID       BIGINT                                                                          NOT NULL,
    BAIRRO          VARCHAR(100)                                                                    NOT NULL,
    CEP             VARCHAR(8)                                                                      NOT NULL,
    CIDADE          VARCHAR(100)                                                                    NOT NULL,
    COMPLEMENTO     VARCHAR(255),
    ESTADO          VARCHAR(2)                                                                      NOT NULL,
    NUMERO          VARCHAR(50)                                                                     NOT NULL,
    PRINCIPAL       BIT                                                                             NOT NULL,
    RUA             VARCHAR(255)                                                                    NOT NULL,
    TIPO            ENUM ('COBRANCA','COMERCIAL','CORRESPONDENCIA','ENTREGA','OUTRO','RESIDENCIAL') NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_CONTACTS
(
    ID              BIGINT                                                                                             NOT NULL AUTO_INCREMENT,
    CREATED_AT      DATETIME(6),
    CREATED_BY      BIGINT,
    DELETED         BIT,
    DELETED_AT      DATETIME(6),
    UPDATED_AT      DATETIME(6),
    UPDATED_BY      BIGINT,
    VERSION         BIGINT,
    SCOPE           ENUM ('GLOBAL','GROUP','TENANT'),
    TENANT_GROUP_ID BIGINT,
    TENANT_ID       BIGINT                                                                                             NOT NULL,
    ATIVO           BIT                                                                                                NOT NULL,
    DESCRICAO       VARCHAR(255),
    PRINCIPAL       BIT                                                                                                NOT NULL,
    TIPO            ENUM ('CELULAR','EMAIL','FACEBOOK','INSTAGRAM','LINKEDIN','OUTRO','TELEFONE','WEBSITE','WHATSAPP') NOT NULL,
    VALOR           VARCHAR(255)                                                                                       NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_PERMISSION
(
    ID              BIGINT                                         NOT NULL AUTO_INCREMENT,
    CREATED_AT      DATETIME(6),
    CREATED_BY      BIGINT,
    DELETED         BIT,
    DELETED_AT      DATETIME(6),
    UPDATED_AT      DATETIME(6),
    UPDATED_BY      BIGINT,
    VERSION         BIGINT,
    SCOPE           ENUM ('GLOBAL','GROUP','TENANT'),
    TENANT_GROUP_ID BIGINT,
    TENANT_ID       BIGINT                                         NOT NULL,
    ACTION          ENUM ('VIEW','CREATE','EDIT','DELETE','OTHER') NOT NULL,
    CODE            VARCHAR(255)                                   NOT NULL,
    MODULE          VARCHAR(255)                                   NOT NULL,
    NAME            VARCHAR(255)                                   NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_ROLE
(
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    CREATED_AT      DATETIME(6),
    CREATED_BY      BIGINT,
    DELETED         BIT,
    DELETED_AT      DATETIME(6),
    UPDATED_AT      DATETIME(6),
    UPDATED_BY      BIGINT,
    VERSION         BIGINT,
    SCOPE           ENUM ('GLOBAL','GROUP','TENANT'),
    TENANT_GROUP_ID BIGINT,
    TENANT_ID       BIGINT       NOT NULL,
    NAME            VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_ROLE_PERMISSION
(
    ROLE_ID       BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TENANT_GROUP
(
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    ACTIVE      BIT          NOT NULL,
    CREATED_AT  DATETIME(6)  NOT NULL,
    DESCRIPTION VARCHAR(500),
    NAME        VARCHAR(255) NOT NULL,
    UPDATED_AT  DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT
(
    ID               BIGINT       NOT NULL AUTO_INCREMENT,
    ACTIVE           BIT          NOT NULL,
    CREATED_AT       DATETIME(6)  NOT NULL,
    EMAIL            VARCHAR(150) NOT NULL,
    NAME             VARCHAR(200) NOT NULL,
    PHONE            VARCHAR(20),
    TRIAL            BIT          NOT NULL,
    TRIAL_EXPIRES_AT DATETIME(6),
    UPDATED_AT       DATETIME(6),
    PLAN_ID          BIGINT       NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_ALLOW_DOMAINS
(
    ID         BIGINT                      NOT NULL AUTO_INCREMENT,
    ACTIVE     BIT                         NOT NULL,
    CREATED_AT DATETIME(6)                 NOT NULL,
    DOMAIN     VARCHAR(255)                NOT NULL,
    TYPE       ENUM ('CORS','EMAIL','SSO') NOT NULL,
    TENANT_ID  BIGINT                      NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_CONFIG
(
    ID               BIGINT       NOT NULL AUTO_INCREMENT,
    ALLOW_API_ACCESS BIT          NOT NULL,
    APP_DESCRIPTION  VARCHAR(500),
    APP_NAME         VARCHAR(150) NOT NULL,
    CREATED_AT       DATETIME(6)  NOT NULL,
    MAINTENANCE_MODE BIT          NOT NULL,
    MULTI_BRANCH     BIT          NOT NULL,
    ONBOARDING_DONE  BIT          NOT NULL,
    SLUG             VARCHAR(100) NOT NULL,
    SUPPORT_EMAIL    VARCHAR(150),
    UPDATED_AT       DATETIME(6),
    WHITE_LABEL      BIT          NOT NULL,
    TENANT_ID        BIGINT       NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_DATASOURCE
(
    ID                 BIGINT                                                                                                                                                               NOT NULL AUTO_INCREMENT,
    ACTIVE             BIT                                                                                                                                                                  NOT NULL,
    CONNECTION_TIMEOUT INTEGER,
    CREATED_AT         DATETIME(6)                                                                                                                                                          NOT NULL,
    DB_TYPE            ENUM ('CLICKHOUSE','COCKROACHDB','DB2','DERBY','FIREBIRD','H2','HSQLDB','INFORMIX','MARIADB','MYSQL','ORACLE','POSTGRESQL','SQLITE','SQL_SERVER','SYBASE','VERTICA') NOT NULL,
    DRIVER_CLASS       VARCHAR(200)                                                                                                                                                         NOT NULL,
    IDLE_TIMEOUT       INTEGER,
    PASSWORD_ENCRYPTED VARCHAR(500)                                                                                                                                                         NOT NULL,
    POOL_MAX           INTEGER,
    POOL_MIN           INTEGER,
    SCHEMA_NAME        VARCHAR(100),
    TEST_STATUS        ENUM ('FAILED','PENDING','SUCCESS'),
    TESTED_AT          DATETIME(6),
    UPDATED_AT         DATETIME(6),
    URL                VARCHAR(500)                                                                                                                                                         NOT NULL,
    USERNAME           VARCHAR(100)                                                                                                                                                         NOT NULL,
    TENANT_ID          BIGINT                                                                                                                                                               NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_FEATURES
(
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    ACTIVE      BIT          NOT NULL,
    BEAN_NAME   VARCHAR(200) NOT NULL,
    CREATED_AT  DATETIME(6)  NOT NULL,
    DESCRIPTION VARCHAR(500),
    FEATURE_KEY VARCHAR(100) NOT NULL,
    UPDATED_AT  DATETIME(6),
    TENANT_ID   BIGINT       NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_FISCAL
(
    ID                 BIGINT       NOT NULL AUTO_INCREMENT,
    CITY_REGISTRATION  VARCHAR(20),
    CNPJ               VARCHAR(14)  NOT NULL,
    CREATED_AT         DATETIME(6)  NOT NULL,
    LEGAL_NAME         VARCHAR(150) NOT NULL,
    STATE_REGISTRATION VARCHAR(20),
    TAX_REGIME         VARCHAR(50),
    TRADE_NAME         VARCHAR(150),
    UPDATED_AT         DATETIME(6),
    TENANT_ID          BIGINT       NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_GROUP_TNT
(
    TNT_GROUP_ID BIGINT NOT NULL,
    TNT_ID       BIGINT NOT NULL,
    PRIMARY KEY (TNT_GROUP_ID, TNT_ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_PLAN
(
    ID            BIGINT         NOT NULL AUTO_INCREMENT,
    ACTIVE        BIT            NOT NULL,
    CREATED_AT    DATETIME(6)    NOT NULL,
    DESCRIPTION   VARCHAR(500),
    MAX_USERS     INTEGER        NOT NULL,
    MONTHLY_PRICE DECIMAL(10, 2) NOT NULL,
    NAME          VARCHAR(100)   NOT NULL,
    UPDATED_AT    DATETIME(6),
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_SECURITY
(
    ID                       BIGINT      NOT NULL AUTO_INCREMENT,
    CREATED_AT               DATETIME(6) NOT NULL,
    LOCKOUT_DURATION_MIN     INTEGER,
    MAX_LOGIN_ATTEMPTS       INTEGER,
    MIN_PASSWORD_LENGTH      INTEGER,
    PASSWORD_EXPIRATION_DAYS INTEGER,
    REQUIRE_NUMBER           BIT         NOT NULL,
    REQUIRE_SPECIAL          BIT         NOT NULL,
    REQUIRE_UPPERCASE        BIT         NOT NULL,
    UPDATED_AT               DATETIME(6),
    TENANT_ID                BIGINT      NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_TNT_VISUAL
(
    ID                   BIGINT      NOT NULL AUTO_INCREMENT,
    BACKGROUND_IMAGE_URL VARCHAR(500),
    BORDER_RADIUS        VARCHAR(20),
    COLOR_ACCENT         VARCHAR(7),
    COLOR_BACKGROUND     VARCHAR(7),
    COLOR_DANGER         VARCHAR(7),
    COLOR_PRIMARY        VARCHAR(7),
    COLOR_SECONDARY      VARCHAR(7),
    COLOR_SUCCESS        VARCHAR(7),
    COLOR_TEXT           VARCHAR(7),
    COLOR_WARNING        VARCHAR(7),
    CREATED_AT           DATETIME(6) NOT NULL,
    EMAIL_LOGO_URL       VARCHAR(500),
    FAVICON_URL          VARCHAR(500),
    FONT_CDN_URL         VARCHAR(500),
    FONT_FAMILY          VARCHAR(100),
    LOGO_LARGE_URL       VARCHAR(500),
    LOGO_URL             VARCHAR(500),
    SIDEBAR_COLLAPSED    BIT         NOT NULL,
    THEME                VARCHAR(50),
    UPDATED_AT           DATETIME(6),
    TENANT_ID            BIGINT      NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_USER
(
    ID            BIGINT                                                             NOT NULL AUTO_INCREMENT,
    CREATED_AT    DATETIME(6),
    CREATED_BY    BIGINT,
    DELETED       BIT,
    DELETED_AT    DATETIME(6),
    UPDATED_AT    DATETIME(6),
    UPDATED_BY    BIGINT,
    VERSION       BIGINT,
    APPROVED_AT   DATETIME(6),
    APPROVED_BY   BIGINT,
    CPF           VARCHAR(255)                                                       NOT NULL,
    EMAIL         VARCHAR(255)                                                       NOT NULL,
    NAME          VARCHAR(255)                                                       NOT NULL,
    PASSWORD_HASH VARCHAR(255)                                                       NOT NULL,
    STATUS        ENUM ('APPROVE_PENDING','BLOCKED','DISABLED','ENABLED','REJECTED') NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE TB_USER_CONTACT
(
    USER_ID    BIGINT NOT NULL,
    CONTACT_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, CONTACT_ID)
) ENGINE = InnoDB;

CREATE TABLE TB_USER_PERMISSION
(
    USER_ID       BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, PERMISSION_ID)
) ENGINE = InnoDB;

CREATE TABLE TB_USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
) ENGINE = InnoDB;

CREATE TABLE TB_USER_TNT
(
    USER_ID BIGINT NOT NULL,
    TNT_ID  BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, TNT_ID)
) ENGINE = InnoDB;

ALTER TABLE TB_ROLE_PERMISSION
    ADD CONSTRAINT UKG7V1TR7UO3KF265HEXPLC4XVV UNIQUE (PERMISSION_ID);

CREATE INDEX IDX_TENANT_GROUP_ACTIVE ON TB_TENANT_GROUP (ACTIVE);

CREATE INDEX IDX_TENANT_ALLOW_DOMAINS_TENANT_ID ON TB_TNT_ALLOW_DOMAINS (TENANT_ID);

ALTER TABLE TB_TNT_ALLOW_DOMAINS
    ADD CONSTRAINT UKRLSG28H08NKOUCGFTB1TWRAUD UNIQUE (TENANT_ID, DOMAIN);

ALTER TABLE TB_TNT_CONFIG
    ADD CONSTRAINT UKFXYA4IKQAIN54SO79FUW32KPW UNIQUE (TENANT_ID);

CREATE INDEX IDX_TENANT_DATASOURCE_TENANT_ID ON TB_TNT_DATASOURCE (TENANT_ID);

CREATE INDEX IDX_TENANT_DATASOURCE_ACTIVE ON TB_TNT_DATASOURCE (ACTIVE);

ALTER TABLE TB_TNT_DATASOURCE
    ADD CONSTRAINT UK9VVEYTE2PQLBX954QJAFVBOIH UNIQUE (TENANT_ID);

CREATE INDEX IDX_TENANT_FEATURES_TENANT_ID ON TB_TNT_FEATURES (TENANT_ID);

CREATE INDEX IDX_TENANT_FEATURES_ACTIVE ON TB_TNT_FEATURES (ACTIVE);

ALTER TABLE TB_TNT_FEATURES
    ADD CONSTRAINT UK1EPCLAJMQMJ3LGIJ5I49IISAF UNIQUE (TENANT_ID, FEATURE_KEY);

ALTER TABLE TB_TNT_FISCAL
    ADD CONSTRAINT UK1GO9A7WOA7YYTKL6BBHYVQIMU UNIQUE (TENANT_ID);

ALTER TABLE TB_TNT_FISCAL
    ADD CONSTRAINT UKLT2ESGYL2JGLLNBKRWANAKH3E UNIQUE (CNPJ);

ALTER TABLE TB_TNT_SECURITY
    ADD CONSTRAINT UKAAXB6CVS7W8E8HX8NN5L3P8A3 UNIQUE (TENANT_ID);

ALTER TABLE TB_TNT_VISUAL
    ADD CONSTRAINT UKB90N2C9P2CJ0BFNVAQF1I6YOC UNIQUE (TENANT_ID);

ALTER TABLE TB_USER
    ADD CONSTRAINT UK869SA3REBUF3NM0D4JWXDTOUK UNIQUE (CPF);

ALTER TABLE TB_USER
    ADD CONSTRAINT UK4VIH17MUBE9J7CQYJLFBCRK4M UNIQUE (EMAIL);

ALTER TABLE TB_USER_CONTACT
    ADD CONSTRAINT UK6EAOE63EXXESFELBOTOBXWV7F UNIQUE (CONTACT_ID);

ALTER TABLE TB_USER_PERMISSION
    ADD CONSTRAINT UK44W3GAQXMTFVN2XSLNG1A5PI0 UNIQUE (PERMISSION_ID);

ALTER TABLE TB_USER_ROLE
    ADD CONSTRAINT UK1TXPCISCO2L99TL5QQSHR6PTP UNIQUE (ROLE_ID);

ALTER TABLE TB_USER_TNT
    ADD CONSTRAINT UKIV97FE2SU39QD9WW0VJ96TI92 UNIQUE (TNT_ID);

ALTER TABLE TB_ROLE_PERMISSION
    ADD CONSTRAINT FKN1FUQ85QVJB8I00N532HJI0K5 FOREIGN KEY (PERMISSION_ID) REFERENCES TB_PERMISSION (ID);

ALTER TABLE TB_ROLE_PERMISSION
    ADD CONSTRAINT FKOPY61IG7UC3G8PC5XKY4C9SQS FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ID);

ALTER TABLE TB_TNT
    ADD CONSTRAINT FKIUOQTMR51CHSEBYOIEL7FI4GJ FOREIGN KEY (PLAN_ID) REFERENCES TB_TNT_PLAN (ID);

ALTER TABLE TB_TNT_ALLOW_DOMAINS
    ADD CONSTRAINT FKH2HFST1LAICHN7B9PABXPPF61 FOREIGN KEY (TENANT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_TNT_CONFIG
    ADD CONSTRAINT FK24412V0F2ABULGCKLVL88NTQ0 FOREIGN KEY (TENANT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_TNT_DATASOURCE
    ADD CONSTRAINT FKOLFT6U9CDQTLTK5OD8FI3WDPJ FOREIGN KEY (TENANT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_TNT_FEATURES
    ADD CONSTRAINT FKN6OX8RO48O16TAQLMPF4P94JB FOREIGN KEY (TENANT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_TNT_FISCAL
    ADD CONSTRAINT FKKCWPSDR9BIICCUYCQBYUEIPBP FOREIGN KEY (TENANT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_TNT_GROUP_TNT
    ADD CONSTRAINT FKRA6XV7GFKQDKJAB0FDGPQ7QHR FOREIGN KEY (TNT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_TNT_GROUP_TNT
    ADD CONSTRAINT FKFV5AAGMKDPLDXS9OMAKE8IXW6 FOREIGN KEY (TNT_GROUP_ID) REFERENCES TB_TENANT_GROUP (ID);

ALTER TABLE TB_TNT_SECURITY
    ADD CONSTRAINT FKKFHFAGFLMQEAUXFJWLSC45G8S FOREIGN KEY (TENANT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_TNT_VISUAL
    ADD CONSTRAINT FKS5Y36AD5XPTJH6L247Q87A2X8 FOREIGN KEY (TENANT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_USER_CONTACT
    ADD CONSTRAINT FKA67D7O0DT7QDHBY08X6ERV3BN FOREIGN KEY (CONTACT_ID) REFERENCES TB_CONTACTS (ID);

ALTER TABLE TB_USER_CONTACT
    ADD CONSTRAINT FKLHGJ4R45VL0IOA06Q7DGAM6N0 FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID);

ALTER TABLE TB_USER_PERMISSION
    ADD CONSTRAINT FKJHGG2P2M7J547G6WL1DUR8SGA FOREIGN KEY (PERMISSION_ID) REFERENCES TB_PERMISSION (ID);

ALTER TABLE TB_USER_PERMISSION
    ADD CONSTRAINT FKOOH8T1QMJ769TTJNSQTIERIQB FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID);

ALTER TABLE TB_USER_ROLE
    ADD CONSTRAINT FKEA2OOTW6B6BB0XT3PTL28BYMV FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ID);

ALTER TABLE TB_USER_ROLE
    ADD CONSTRAINT FK7VN3H53D0TQDIMM8CP45GC0KL FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID);

ALTER TABLE TB_USER_TNT
    ADD CONSTRAINT FK5D22DDKOOK556EFNCTJJ2F58K FOREIGN KEY (TNT_ID) REFERENCES TB_TNT (ID);

ALTER TABLE TB_USER_TNT
    ADD CONSTRAINT FKQY6U5X9J7TRPATC0W97NLFAXK FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID);