-- ==================================================================================
-- DATASOURCES CONFIGURATION
-- ==================================================================================
-- Datasources para Tenants 1-10 (MySQL - bancos dedicados)
INSERT INTO TB_TNT_DATASOURCE (TENANT_ID,
                               ACTIVE,
                               CREATED_AT,
                               DB_TYPE,
                               DRIVER_CLASS,
                               PASSWORD_ENCRYPTED,
                               POOL_MAX,
                               POOL_MIN,
                               URL,
                               USERNAME)
VALUES (1,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_HECE',
        'root'),
       (2,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_TECHSOLUTIONS',
        'root'),
       (3,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_LOGISTICA',
        'root'),
       (4,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_VAREJO',
        'root'),
       (5,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_FARMASAUDE',
        'root'),
       (6,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_AUTOPECAS',
        'root'),
       (7,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_CONSTRUMAX',
        'root'),
       (8,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_ELETROTECH',
        'root'),
       (9,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_ALIMENTOSNATURAIS',
        'root'),
       (10,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_MODASTYLE',
        'root');


-- Datasources para Tenants 11-50 (Diversos DB Types)
INSERT INTO TB_TNT_DATASOURCE (TENANT_ID,
                               ACTIVE,
                               CREATED_AT,
                               DB_TYPE,
                               DRIVER_CLASS,
                               PASSWORD_ENCRYPTED,
                               POOL_MAX,
                               POOL_MIN,
                               URL,
                               USERNAME)
VALUES
#     (11,
#         1,
#         NOW(),
#         'POSTGRESQL',
#         'org.postgresql.Driver',
#         '12345',
#         20,
#         5,
#         'jdbc:postgresql://localhost:5432/POSTGRES_TEST',
#         'USER'),
#        (12,
#         1,
#         NOW(),
#         'ORACLE',
#         'oracle.jdbc.driver.OracleDriver',
#         '12345',
#         20,
#         5,
#         'jdbc:oracle:thin:@localhost:1521:ORCL',
#         'system'),
#        (13,
#         1,
#         NOW(),
#         'SQL_SERVER',
#         'com.microsoft.sqlserver.jdbc.SQLServerDriver',
#         'SqlS3rverPass!',
#         20,
#         5,
#         'jdbc:sqlserver://localhost:1433;databaseName=ERPAPI_TEST',
#         'sa'),
       #     (
       #         14,
       #         1,
       #         NOW(),
       #         'MARIADB',
       #         'org.mariadb.jdbc.Driver',
       #         '12345',
       #         20,
       #         5,
       #         'jdbc:mariadb://localhost:3307/ERPAPI_TEST',
       #         'root'
       #     ),
       #     (15, 1, NOW(), 'H2', 'org.h2.Driver', '', 20, 5, 'jdbc:h2:mem:testdb', 'sa'),
       #     (
       #         16,
       #         1,
       #         NOW(),
       #         'DB2',
       #         'com.ibm.db2.jcc.DB2Driver',
       #         '12345',
       #         20,
       #         5,
       #         'jdbc:db2://localhost:50000/testdb',
       #         'db2inst1'
       #     ),
#        (17,
#         1,
#         NOW(),
#         'SQLITE',
#         'org.sqlite.JDBC',
#         '',
#         20,
#         5,
#         'jdbc:sqlite:erpapi.db',
#         'sa'),
#        (18,
#         1,
#         NOW(),
#         'COCKROACHDB',
#         'org.postgresql.Driver',
#         '',
#         20,
#         5,
#         'jdbc:postgresql://localhost:26257/defaultdb',
#         'root'),
#        (19,
#         1,
#         NOW(),
#         'SYBASE',
#         'com.sybase.jdbc4.jdbc.SybDriver',
#         '12345',
#         20,
#         5,
#         'jdbc:sybase:Tds:localhost:5000/testdb',
#         'sa'),
       (20,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
#        (21,
#         1,
#         NOW(),
#         'FIREBIRD',
#         'org.firebirdsql.jdbc.FBDriver',
#         'masterkey',
#         20,
#         5,
#         'jdbc:firebirdsql://localhost:3050/testdb',
#         'sysdba'),
#        (22,
#         1,
#         NOW(),
#         'DERBY',
#         'org.apache.derby.jdbc.ClientDriver',
#         '',
#         20,
#         5,
#         'jdbc:derby://localhost:1527/testdb',
#         'sa'),
#        (23,
#         1,
#         NOW(),
#         'HSQLDB',
#         'org.hsqldb.jdbc.JDBCDriver',
#         '',
#         20,
#         5,
#         'jdbc:hsqldb:hsql://localhost:9001/testdb',
#         'sa'),
       (24,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
#        (25,
#         1,
#         NOW(),
#         'CLICKHOUSE',
#         'com.clickhouse.jdbc.ClickHouseDriver',
#         '',
#         20,
#         5,
#         'jdbc:clickhouse://localhost:8123/default',
#         'default'),
       (26,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (27,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (28,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (29,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (30,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (31,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (32,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (33,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (34,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (35,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (36,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (37,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (38,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (39,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (40,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (41,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (42,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (43,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (44,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (45,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (46,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (47,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (48,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (49,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root'),
       (50,
        1,
        NOW(),
        'MYSQL',
        'com.mysql.cj.jdbc.Driver',
        '12345',
        20,
        5,
        'jdbc:mysql://localhost:3306/ERPAPI_SHARED',
        'root');